<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * followed by relations of table "producto" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $precio
 * @property string $descripcion
 *
 * @property Pedido[] $pedidos
 */
abstract class BaseProducto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'producto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Producto|Productos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('precio', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>100),
			array('descripcion', 'safe'),
			array('nombre, precio, descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, precio, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pedidos' => array(self::HAS_MANY, 'Pedido', 'producto_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'precio' => Yii::t('app', 'Precio'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'pedidos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('precio', $this->precio);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}