<?php

/**
 * This is the model base class for the table "mensaje".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mensaje".
 *
 * Columns in table "mensaje" available as properties of the model,
 * followed by relations of table "mensaje" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_emisor
 * @property integer $user_receptor
 * @property string $fecha
 * @property string $mensaje
 * @property string $estado
 *
 * @property User $userEmisor
 * @property User $userReceptor
 */
abstract class BaseMensaje extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mensaje';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mensaje|Mensajes', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('user_emisor, user_receptor', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>45),
			array('fecha, mensaje', 'safe'),
			array('user_emisor, user_receptor, fecha, mensaje, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_emisor, user_receptor, fecha, mensaje, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'userEmisor' => array(self::BELONGS_TO, 'User', 'user_emisor'),
			'userReceptor' => array(self::BELONGS_TO, 'User', 'user_receptor'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_emisor' => null,
			'user_receptor' => null,
			'fecha' => Yii::t('app', 'Fecha'),
			'mensaje' => Yii::t('app', 'Mensaje'),
			'estado' => Yii::t('app', 'Estado'),
			'userEmisor' => null,
			'userReceptor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_emisor', $this->user_emisor);
		$criteria->compare('user_receptor', $this->user_receptor);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('mensaje', $this->mensaje, true);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}