<?php

/**
 * This is the model base class for the table "pedido".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pedido".
 *
 * Columns in table "pedido" available as properties of the model,
 * followed by relations of table "pedido" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $producto_id
 * @property integer $cantidad
 * @property integer $total
 * @property string $estado
 *
 * @property Producto $producto
 * @property User $user
 */
abstract class BasePedido extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pedido';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pedido|Pedidos', $n);
	}

	public static function representingColumn() {
		return 'estado';
	}

	public function rules() {
		return array(
			array('user_id, producto_id, cantidad, total', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>45),
			array('user_id, producto_id, cantidad, total, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, producto_id, cantidad, total, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'producto' => array(self::BELONGS_TO, 'Producto', 'producto_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'producto_id' => null,
			'cantidad' => Yii::t('app', 'Cantidad'),
			'total' => Yii::t('app', 'Total'),
			'estado' => Yii::t('app', 'Estado'),
			'producto' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('producto_id', $this->producto_id);
		$criteria->compare('cantidad', $this->cantidad);
		$criteria->compare('total', $this->total);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}